# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6)),
                ('student_name', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(verbose_name='date issued')),
            ],
        ),
    ]
