# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170119_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 19, 18, 49, 384428)),
        ),
    ]
